CREATE TABLE Orders
(
	ID INT NOT NULL,
	CustomerID INT FOREIGN KEY REFERENCES [Customers] (ID),
	ProductID INT FOREIGN KEY REFERENCES [Products] (ID),
	[Value] INT NOT NULL,
	OrderCost MONEY NOT NULL,
	DateOrder DATETIME NOT NULL,
	IndOrd INT
	PRIMARY KEY (ID)
)
